# Generated by Django 5.0.7 on 2024-10-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
    ]
