# Generated by Django 5.1.2 on 2024-10-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro',
            field=models.CharField(default='', max_length=150),
        ),
    ]
