# Generated by Django 5.0.7 on 2024-11-16 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('length', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('voting', 'voting'), ('confirming', 'confirming'), ('completed', 'completed')], default='created', max_length=10)),
                ('accept_members', models.ManyToManyField(related_name='promises_accept', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='promises', to=settings.AUTH_USER_MODEL)),
                ('reject_members', models.ManyToManyField(related_name='promises_reject', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='promise.promise')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='promise.promise')),
            ],
        ),
        migrations.CreateModel(
            name='PromiseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('length', models.IntegerField()),
                ('members_can_attend', models.ManyToManyField(related_name='participants_of_promise_options', to=settings.AUTH_USER_MODEL)),
                ('vote_members', models.ManyToManyField(related_name='voted_promise_options', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='promise',
            name='promise_options',
            field=models.ManyToManyField(blank=True, related_name='promises', to='promise.promiseoption'),
        ),
    ]
