# Generated by Django 5.1.2 on 2024-10-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promise',
            name='promise_option',
        ),
        migrations.AddField(
            model_name='promise',
            name='promise_options',
            field=models.ManyToManyField(blank=True, related_name='promises', to='promise.promiseoption'),
        ),
    ]
