# Generated by Django 5.1.2 on 2024-10-31 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0002_remove_promise_promise_option_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promiseoption',
            name='user',
        ),
        migrations.AddField(
            model_name='promiseoption',
            name='members_can_attend',
            field=models.ManyToManyField(related_name='participants_of_promise_options', to=settings.AUTH_USER_MODEL),
        ),
    ]
