# Generated by Django 5.1.2 on 2024-11-01 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0003_remove_promiseoption_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='accept_members',
            field=models.ManyToManyField(related_name='promises_accept', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promise',
            name='reject_members',
            field=models.ManyToManyField(related_name='promises_reject', to=settings.AUTH_USER_MODEL),
        ),
    ]
