# Generated by Django 5.1.2 on 2024-11-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0006_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promiseoption',
            name='title',
        ),
    ]
