# Generated by Django 5.1.2 on 2024-11-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        ('promise', '0005_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='promise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promise_creates_this_plan', to='promise.promise'),
        ),
    ]
