# Generated by Django 5.0.7 on 2024-10-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_plan_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
