# Generated by Django 5.0.7 on 2024-11-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('plan', 'Plan'), ('promise', 'Promise'), ('friend', 'Friend')], default='plan', max_length=20),
        ),
    ]
